using DSCC.MVC._7924.Models;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace DSCC.MVC._7924.Controllers
{
    public class ClientController : Controller
    {
        // GET: Client
        //the Baseurl is link generated by Elastic Beanstalk
        string Baseurl = "http://dsccmicroservicesapi7924-dev.us-east-2.elasticbeanstalk.com";
        private string urlStarter = "/api/Client";
        public async Task<ActionResult> Index()
        {
            //the list of Clients
            var clientList = new List<Client>();
            string bodyResponse = null;
            //creating HttpClient
            var client = new HttpClient();
            var response = await client.GetAsync(Baseurl + urlStarter);
            if (response.IsSuccessStatusCode)
            {
                bodyResponse = await response.Content.ReadAsStringAsync();
                clientList = JsonConvert.DeserializeObject<List<Client>>(bodyResponse);
            }

            return View(clientList);
        }

        // GET: ClientsController/Details/5
        //Getting the Client item
        public async Task<ActionResult> Details(int id)
        {
            Client item = await GetClient(id);

            return View(item);
        }

        // GET: ClientsController/Create
        //Create method returning the View
        public ActionResult Create()
        {
            return View();
        }

        // POST: ClientsController/Create
        //Create method used for creating client object, which gets API from MicroservicesAPI
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Client collection)
        {
            try
            {
                var client = new HttpClient();
                var jsonSerializer = JsonConvert.SerializeObject(collection);
                var data = new StringContent(jsonSerializer, Encoding.UTF8, "application/json");
                var response = await client.PostAsync(Baseurl + urlStarter, data);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ClientsController/Edit/5
        //Edit Method returning the View
        public async Task<ActionResult> Edit(int id)
        {
            Client item = await GetClient(id);
            return View(item);
        }

        // POST: ClientsController/Edit/5
        //Editing method for modifying client with specified id
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, Client collection)
        {
            try
            {
                var client = new HttpClient();
                var jsonSerializer = JsonConvert.SerializeObject(collection);
                var data = new StringContent(jsonSerializer, Encoding.UTF8, "application/json");
                var response = await client.PutAsync(Baseurl + urlStarter + "/" + id, data);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ClientsController/Delete/5
        //Getting item with specified Id in order to delete
        public async Task<ActionResult> Delete(int id)
        {
             Client item = await GetClient(id);
             return View(item); 
        }

        // POST: ClientsController/Delete/5
        //The method to delete item with specified Id
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, Client collection)
        {
            try
            {
                var client = new HttpClient();
                var response = await client.DeleteAsync(Baseurl + urlStarter + "/" + id);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        //Getting client with a specified Id
        public async Task<Client> GetClient(int id)
        {
            Client item = null;
            var client = new HttpClient();
            var response = await client.GetAsync(Baseurl + urlStarter + "/" + id);
            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                item = JsonConvert.DeserializeObject<Client>(content);
            }
            return item;
        }
    }
}
